version: "3.9"
services:
  node:
    image: djinno/subspace-node
    environment:
    - CHAIN=testnet
    - NODE_NAME=djinn
    network_mode: host
  farmer:
    image: djinno/subspace-farmer
    environment:
    - SUBSPACE_ADDRESS=5CtbQ16UKQN9kyttrJytMWcZ9HrQR4ZfPRwC3sfHhvoSCS9u
    restart: always
    network_mode: host
    depends_on:
    - node
