version: "3.9"
services:
  node:
    environment:
    - CHAIN=testnet
    - NODE_NAME=djinn
    build:
      context: .
      dockerfile: node.Dockerfile
    network_mode: host
  farmer:
    environment:
    - SUBSPACE_ADDRESS=5CtbQ16UKQN9kyttrJytMWcZ9HrQR4ZfPRwC3sfHhvoSCS9u
    build:
      context: .
      dockerfile: farmer.Dockerfile
    restart: always
    network_mode: host
    depends_on:
    - node
